import fs from "node:fs";
const path = "ml/i18n/ui_strings.json";
const data = JSON.parse(fs.readFileSync(path, "utf8"));
const additions = {
  en: { title_possible: "Possible conditions", title_emergency: "Emergency", title_greeting: "Hello", title_unknown: "Tell me more", mentioned: "You mentioned", common_symptoms: "Common symptoms", what_to_do: "What you can do", when_doctor: "When to see a doctor", follow_up: "Could you share one or two more symptoms?", cautious: "These symptoms are common and could relate to many conditions; I cannot narrow this down confidently.", generic_care: "Rest, drink fluids, and monitor how you feel.", examples: ["I have fever and headache", "What are the symptoms of diabetes?", "I have itching and a skin rash"], emergency_actions: ["Call your local emergency number now.", "Go to the nearest hospital.", "Do not drive yourself."], no_predictions: "I need at least two recognized symptoms before I can show possible conditions." },
  hi: { title_possible: "संभावित कारण", title_emergency: "आपातकाल", title_greeting: "नमस्ते", title_unknown: "कृपया और बताएं", mentioned: "आपने बताया", common_symptoms: "सामान्य लक्षण", what_to_do: "आप क्या कर सकते हैं", when_doctor: "डॉक्टर से कब मिलें", follow_up: "क्या आप एक या दो और लक्षण बता सकते हैं?", cautious: "ये लक्षण सामान्य हैं और कई कारणों से जुड़े हो सकते हैं; मैं अभी निश्चित रूप से कारण नहीं बता सकता।", generic_care: "आराम करें, तरल पदार्थ लें और अपनी स्थिति पर ध्यान दें।", examples: ["मुझे बुखार और सिरदर्द है", "मधुमेह के लक्षण क्या हैं?", "मुझे खुजली और त्वचा पर दाने हैं"], emergency_actions: ["अभी स्थानीय आपातकालीन नंबर पर कॉल करें।", "निकटतम अस्पताल जाएं।", "खुद गाड़ी न चलाएं।"], no_predictions: "संभावित स्थितियां दिखाने से पहले कम से कम दो पहचाने गए लक्षण बताएं।" },
  gu: { title_possible: "શક્ય કારણો", title_emergency: "કટોકટી", title_greeting: "નમસ્તે", title_unknown: "વધુ જણાવો", mentioned: "તમે જણાવેલા લક્ષણો", common_symptoms: "સામાન્ય લક્ષણો", what_to_do: "તમે શું કરી શકો", when_doctor: "ડૉક્ટરને ક્યારે મળવું", follow_up: "શું તમે એક કે બે વધુ લક્ષણો જણાવી શકો?", cautious: "આ લક્ષણો સામાન્ય છે અને અનેક કારણો સાથે જોડાયેલા હોઈ શકે છે; હું હમણાં ચોક્કસ કારણ જણાવી શકતો નથી.", generic_care: "આરામ કરો, પ્રવાહી લો અને તમારી સ્થિતિ પર નજર રાખો.", examples: ["મને તાવ અને માથું દુખે છે", "ડાયાબિટીસના લક્ષણો શું છે?", "મને ખંજવાળ અને ચામડી પર ચકામા છે"], emergency_actions: ["હમણાં સ્થાનિક ઇમરજન્સી નંબર પર કૉલ કરો.", "નજીકની હોસ્પિટલમાં જાઓ.", "પોતે વાહન ન ચલાવો."], no_predictions: "શક્ય સ્થિતિઓ બતાવવા માટે ઓછામાં ઓછા બે ઓળખાયેલા લક્ષણો જણાવો." }
};
for (const [lang, values] of Object.entries(additions)) Object.assign(data[lang], values);
fs.writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
